vim.pack.add({ "https://github.com/nvim-mini/mini.icons" })

-- Setup --

require("mini.icons").setup({
	default = {
		file = { glyph = "" },
		directory = { glyph = "" },
	},
	extension = {
		js = { glyph = "" },
		ipynb = { glyph = "" },
		jpg = { glyph = "" },
		png = { glyph = "" },
		pdf = { glyph = "" },
	},
	lsp = {
		["function"] = { glyph = "ƒ", hl = "MiniIconsBlue" },
		file = { glyph = "󰈙" },
		folder = { glyph = "󰉋" },
		module = { glyph = "" },
		reference = { glyph = "󰈇" },
		namespace = { glyph = "" },
		package = { glyph = "󰏗" },
		class = { glyph = "󰠱", hl = "MiniIconsYellow" },
		method = { glyph = "ƒ", hl = "MiniIconsBlue" },
		field = { glyph = "󰆨" },
		constructor = { glyph = "" },
		enum = { glyph = "ℰ", hl = "MiniIconsYellow" },
		interface = { glyph = "", hl = "MiniIconsYellow" },
		enummember = { glyph = "" },
		operator = { glyph = "" },
		typeparameter = { glyph = "" },
		variable = { glyph = "", hl = "MiniIconsOrange" },
		constant = { glyph = "", hl = "MiniIconsOrange" },
		string = { glyph = "", hl = "MiniIconsGreen" },
		number = { glyph = "" },
		event = { glyph = "" },
		boolean = { glyph = "" },
		array = { glyph = "󰅪" },
		object = { glyph = "" },
		key = { glyph = "" },
		property = { glyph = "󰜢", hl = "MiniIconsRed" },
		null = { glyph = "" },
		struct = { glyph = "󰙅", hl = "MiniIconsYellow" },
		text = { glyph = "" },
		parameter = { glyph = "", hl = "MiniIconsRed" },
		staticMethod = { glyph = "ƒ", hl = "MiniIconsBlue" },
		macro = { glyph = "" },
		keyword = { glyph = "", hl = "MiniIconsPurple" },
		unit = { glyph = "󰑭" },
		value = { glyph = "" },
		component = { glyph = "󰅴" },
		fragment = { glyph = "󰅴" },
		misc = { glyph = "" },
		typealias = { glyph = "" },
	},
})
require("mini.icons").mock_nvim_web_devicons()
